baseURL = "https://awsworkshop.io"
languageCode = "en-us"
title = "Modernization workshop"
theme = "aws-modernize"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]